CSC207-2022F-UofT/course-project-team-flash

- src/entities/flashcard.java
- src/entities/selectAllFlashcard.java
Started the base of the abstract class flashcard with one concrete subclass selectAllFlashcard for the team to use on their use cases.
> Entities Initial Commit

- src/main/java/createCard/CreateCardController.java
- src/main/java/createCard/CreateCardInputBoundary.java
- src/main/java/createCard/CreateCardInputData.java
- src/main/java/createCard/CreateCardInteractor.java
- src/main/java/createCard/CreateCardOutputBoundary.java
- src/main/java/createCard/CreateCardOutputData.java
- src/main/java/createCard/CreateCardPresenter.java
- src/main/java/entities/CardFactory.java
- src/main/java/entities/Deck.java
- src/main/java/entities/FlashcardFactory.java
- src/main/java/entities/MCFlashcard.java
- src/main/java/entities/QandAFlashcard.java
- src/main/java/entities/SelectAllFlashcard.java
- src/test/java/createCard/CreateCardInputDataTest.java
- src/test/java/entities/DeckTest.java
- src/test/java/entities/MCFlashcardTest.java
- src/test/java/entities/QandAFlashcardTest.java
Completed all Flashcard Entities along with tests
Completed Deck Entity along with tests
Completed CreateCard UseCase not done testing
> Andrew create card feature

- src/main/java/Main.java
- src/main/java/createCard/CreateCardInputData.java
- src/main/java/createCard/CreateCardInteractor.java
- src/main/java/entities/Deck.java
- src/main/java/entities/Flashcard.java
- src/test/java/createCard/CreateCardControllerTest.java
- src/test/java/entities/QandAFlashcardTest.java
Added ids to cards and its creation process
> AndrewCreateCardFeat

- src/main/java/createCard/CreateCardInteractor.java
- src/main/java/createCard/CreateCardOutputBoundary.java
- src/main/java/createCard/CreateCardOutputData.java
- src/main/java/createCard/CreateCardPresenter.java
- src/main/java/entities/CardFactory.java
- src/main/java/entities/FlashcardFactory.java
Fixed FlashcardFactory so that it implements the corresponding interface CardFactory.
Minor Change: Finished up CreateCard use case to include a fail view when either question or answer inputs are left empty.
Presenter: Left incomplete until we decide what information is needed in a future meeting.
Documentation and Test Cases are still to be done.
> Minor Changes Overall to CreateCard and Relevant Entities

- src/main/java/Main.java
- src/main/java/createCard/CreateCardPresenter.java
- src/main/java/enterDeck/EnterDeckController.java
- src/main/java/enterDeck/EnterDeckInputBoundary.java
- src/main/java/enterDeck/EnterDeckInputData.java
- src/main/java/enterDeck/EnterDeckInteractor.java
- src/main/java/enterDeck/EnterDeckOutputBoundary.java
- src/main/java/enterDeck/EnterDeckOutputData.java
- src/main/java/enterDeck/EnterDeckPresenter.java
Created another use case to enter deck which should return a list of cards, but the presenter is still incomplete. 
Minor changes to Main to help Albert get started. (Initialized a few of the creation use cases)
> Andrew enter deck feat

- src/main/java/editCard/EditCardController.java
- src/main/java/editCard/EditCardInputBoundary.java
- src/main/java/editCard/EditCardInputData.java
- src/main/java/editCard/EditCardInteractor.java
- src/main/java/editCard/EditCardOutputBoundary.java
- src/main/java/editCard/EditCardOutputData.java
- src/main/java/editCard/EditCardPresenter.java
Added documentation for EditCard
> Derrick edit card documentation

- src/main/java/screens/CardScreen.java
Card Screen Base to be populated.
> Card Screen

- src/main/java/createCard/CreateCardController.java
- src/main/java/createCard/CreateCardInputBoundary.java
- src/main/java/createCard/CreateCardInputData.java
- src/main/java/createCard/CreateCardInteractor.java
- src/main/java/createCard/CreateCardOutputBoundary.java
- src/main/java/createCard/CreateCardOutputData.java
- src/main/java/createCard/CreateCardPresenter.java
- src/main/java/createDeck/CreateDeckInteractor.java
- src/main/java/editCard/EditCardController.java
- src/main/java/editQuiz/EditQuizController.java
- src/main/java/editQuiz/EditQuizInputBoundary.java
- src/main/java/editQuiz/EditQuizInputData.java
- src/main/java/editQuiz/EditQuizInteractor.java
- src/main/java/editQuiz/EditQuizOutputBoundary.java
- src/main/java/editQuiz/EditQuizOutputData.java
- src/main/java/editQuiz/EditQuizPresenter.java
- src/main/java/entities/FlashcardFactory.java
- src/main/java/entities/Quiz.java
- src/main/java/screens/ViewModel.java
- src/main/java/screens/ViewState.java
1) Finished CreateCard Use Case. Edited documentation and completed presenter
2) Created EditQuiz Use Case with all documentation and implementation completed.
3) Changes to FlashCardFactory to remove select all card
4) Added an additional helper method in Quiz entity
5) Minor changes to view state and additional variables in ViewModel
For anyone reviewing, please be thorough with this one as a lot of changes were made
> Major Changes Made

- src/main/java/createDeck/CreateDeckController.java
- src/main/java/createDeck/CreateDeckInputBoundary.java
- src/main/java/createDeck/CreateDeckInputData.java
- src/main/java/createDeck/CreateDeckInteractor.java
- src/main/java/createDeck/CreateDeckOutputBoundary.java
- src/main/java/createDeck/CreateDeckOutputData.java
- src/main/java/createDeck/CreateDeckPresenter.java
- src/main/java/editQuiz/EditQuizPresenter.java
> Documentation create deck

- src/main/java/deleteCard/DeleteCardController.java
- src/main/java/deleteCard/DeleteCardInputBoundary.java
- src/main/java/deleteCard/DeleteCardInputData.java
- src/main/java/deleteCard/DeleteCardInteractor.java
- src/main/java/deleteCard/DeleteCardOutputBoundary.java
- src/main/java/deleteCard/DeleteCardOutputData.java
- src/main/java/deleteCard/DeleteCardPresenter.java
Created DeleteCard use case with all proper documentation and updated presenter class to reflect changes in viewmodel
> Derrick Delete Card

- src/main/java/editCard/EditCardOutputBoundary.java
- src/main/java/editCard/EditCardPresenter.java
> Changes to edit card, proper implementation of presenter class

- src/main/java/editQuiz/EditQuizPresenter.java
- src/main/java/enterDeck/EnterDeckInteractor.java
- src/main/java/enterDeck/EnterDeckOutputData.java
- src/main/java/enterDeck/EnterDeckPresenter.java
- src/main/java/screens/ViewModel.java
- src/main/java/screens/ViewState.java
> Enter Deck

- src/main/java/screens/ViewModel.java
- Made some variables final
- Added a few more variables for Enter Deck Use Case
> View Model Changes

- src/main/java/Main.java
- src/main/java/screens/CardScreen.java
- src/main/java/screens/DeckScreen.java
- src/main/java/screens/QuizScreen.java
- src/main/java/screens/View.java
Overhaul to CardScreen thanks to Andrew
> Albert aldo user interface

- src/main/java/createQuiz/CreateQuizInteractor.java
- src/main/java/createQuiz/CreateQuizOutputData.java
- Pulled updates from main
- Simplified success view message
- Added new fail view condition to CreateQuizInteractor: decks list is empty
> Updated Create Quiz

- src/main/java/editCard/EditCardInteractor.java
- src/main/java/editCard/EditCardOutputData.java
- src/main/java/editCard/EditCardPresenter.java
Implementation of edit card use case such that it is in line with view model requirements
> Albert edit card

- src/main/java/createQuiz/CreateQuizInputData.java
- src/main/java/createQuiz/CreateQuizInteractor.java
- src/test/java/createQuiz/CreateQuizInteractorTest.java
Fixed error in CreateQuizInteractor, updated CreateQuizInteractorTest
> Fixed error in CreateQuizInteractor, updated CreateQuizInteractorTest

- src/main/java/editCard/EditCardInteractor.java
- src/main/java/editCard/EditCardOutputBoundary.java
- src/main/java/editCard/EditCardPresenter.java
- src/test/java/editCard/EditCardInteractorTest.java
- src/test/java/entities/QandAFlashcardTest.java
Completed the code for EditCardInteractorTest. Coverage is 100% for all classes in editCard usecase except for EditCardOutputData.
I noticed that EditCardInteractor does not have a failview. I added failview methods to the Output Boundary and Presenter. What is left is to add a failview to the Interactor if the new question already exists.
> Jay editCard Tests

- src/main/java/importDeck/ImportDeckInteractor.java
- src/test/java/importDeck/ImportDeckInteractorTest.java
> import deck use case improvements + additional tests

- src/main/java/createDeck/CreateDeckInteractor.java
- src/main/java/editDeck/EditDeckInteractor.java
- src/test/java/entities/QandAFlashcardTest.java
> Minor Changes

- src/main/java/createCard/CreateCardOutputData.java
- src/main/java/editCard/EditCardInteractor.java
- src/main/java/editCard/EditCardOutputData.java
- src/main/java/editCard/EditCardPresenter.java
- src/main/java/screens/CardScreen.java
- src/main/java/screens/View.java
Now can edit multiple choice cards
> Full implementation of edit card use case to card screen

- src/main/java/data/DeckFileImport.java
- src/main/java/data/DeckInMemoryImport.java
- src/main/java/data/DeckPathCleaner.java
- src/test/java/importDeck/ImportDeckInteractorTest.java
> Imported decks should have cleaner names now.

- src/main/java/Main.java
- src/main/java/screens/CardScreen.java
- src/main/java/screens/DeckScreen.java
- src/main/java/screens/View.java
I did my best to refactor CardScreen and I do think it is much cleaner and easy to understand now. Last step will be to add comments. Additionally, the screen has been changed to keep the color choices consistent throughout the program.
> Card Screen DONE! [Not really but almost :)]

- src/main/java/runQuiz/RunQuizInteractor.java
- src/main/java/runQuiz/RunQuizPresenter.java
- src/main/java/runQuiz/ShowProblemOutputData.java
- src/main/java/runQuiz/StartQuizOutputData.java
- src/main/java/screens/ShowAnswerScreen.java
- src/main/java/screens/ShowProblemScreen.java
- src/main/java/screens/View.java
- src/main/java/screens/ViewModel.java
> Revert "Albert Jamie run quiz view"

- src/main/files/Trivia.deck
- src/main/java/runQuiz/RunQuizInteractor.java
- src/main/java/runQuiz/RunQuizPresenter.java
- src/main/java/runQuiz/ShowProblemOutputData.java
- src/main/java/runQuiz/StartQuizOutputData.java
- src/main/java/screens/ShowAnswerScreen.java
- src/main/java/screens/ShowProblemScreen.java
- src/main/java/screens/View.java
- src/main/java/screens/ViewModel.java
- src/test/java/importDeck/ImportDeckInteractorTest.java
Just a small change to fix an error where a QandAFlashcard would crash an active quiz.
> Jamie run quiz view

- src/main/java/runQuiz/RunQuizInteractor.java
- src/main/java/runQuiz/RunQuizPresenter.java
Small change, just added a fail case for the startQuiz use case. A quiz shouldn't be able to be started if there are no flashcards in it, so I added a case for that.
> added fail case for when a quiz contains no flashcards.

- src/main/java/data/DeckFileImport.java
- src/main/java/entities/FlashcardFactory.java
- src/main/java/entities/FlashcardType.java
- src/main/java/importDeck/ImportDeckInteractor.java
- src/test/java/importDeck/ImportDeckInteractorTest.java
also added invalidflashcard enum
> error messages should be nicer now 

- src/main/java/screens/ShowAnswerScreen.java
- src/main/java/screens/ShowProblemScreen.java
I cleaned up both these screens as well as changed the style to be consistent with the rest of the program.
Just view the helper methods to understand what was done.
> Minor Screen Changes

- src/main/java/data/DeckFileExport.java
- src/main/java/exportDeck/ExportDeckInteractor.java
> changed exception message to be cleaner

- src/main/java/enterDeck/EnterDeckInteractor.java
- src/main/java/screens/CardScreen.java
- src/main/java/screens/View.java
In an attempt to implement move card, I found a bug with edit card, which has been corrected. MCFlashcards can now be editted fully. Move card is too much of a hassle.
> Edit Card Bux Fix

- src/main/java/deleteQuiz/DeleteQuizInteractor.java
- src/main/java/enterDeck/EnterDeckInteractor.java
- src/main/java/enterDeck/EnterDeckOutputBoundary.java
- src/main/java/enterDeck/EnterDeckPresenter.java
- src/test/java/deleteQuiz/DeleteQuizInteractorTest.java
- src/test/java/enterDeck/EnterDeckInteractorTest.java
also improved their interactors
> created tests for deleteQuiz and enterDeck, 

- src/main/java/screens/View.java
Edit Deck now changes the corresponding decks stored in quizzes
> Last Minute Bug Fixes

- src/main/java/screens/ShowProblemScreen.java
> ABSOLUTE FINAL CHANGE

- src/main/java/deleteQuiz/DeleteQuizInteractor.java
- src/main/java/enterDeck/EnterDeckInteractor.java
- src/main/java/enterDeck/EnterDeckOutputBoundary.java
- src/main/java/enterDeck/EnterDeckPresenter.java
- src/test/java/deleteQuiz/DeleteQuizInteractorTest.java
- src/test/java/enterDeck/EnterDeckInteractorTest.java
> deletequiz and enterdeck tests

- src/main/java/data/DeckFileExport.java
so if the user wants to save the file to a non-existing directory, the program creates them (if it has permission)
> ability for new directories to be created while exporting
